### PR TITLE
Add modified intro python lesson

### PR DESCRIPTION
**Pull request by aays**
This version of the lesson is largely based on [Madeleine's](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/python/intro/IntroPython-MB.ipynb), save for a few minor differences in the first half. 

At the end, I've added some brief `seaborn`, and also use `sns.load_dataset` to load in a built-in dataset instead of having participants download a file.

### CODE REVIEW

**Comment by QuLogic** [comment]
Checking `type(x) == int` really should be `isinstance(x, int)`.

**Comment by QuLogic** [comment]
Also, no spaces around function keyword arguments; this isn't R.

**Comment by aays** [comment]
Thanks - notebook's been updated to reflect the feedback. 

(and spaces around arguments removed... curse you, PEP8!)

**Comment by QuLogic** [comment]
I'm not sure if you are going to mention PEP8, but for docstrings you can also mention numpydoc or google docstring styles. Both are supported by sphinx's napoleon extension and are less verbose than sphinx's default reST. With sphinx, you can make nice HTML docs from your code. (You don't necessarily need to mention all this of course.)

**Comment by QuLogic** [comment]
BTW, I tried this out on someone who just installed anaconda and `%matplotlib inline` didn't seem to be necessary. I think soon we won't need to recommend this.

**Pull request merged**
