### PR TITLE
Add Cartography lesson.

### PR DESCRIPTION
**Pull request by QuLogic**
Hey, so I've written the Cartopy portion of the Cartography lesson here. I was thinking of touching on folium as well, but I'm not too sure how much time  that'd take. I could of course fill this out with a bit more stuff and focus on Cartopy only, too.

Let me know how full you think it looks and then I'll see about the folium part.

PS, the markdown was converted from the notebook file, so it may or may not look very pretty.

### CODE REVIEW

**Comment by QuLogic** [comment]
PS, there's a zip for people to download here; I'll post it on the event issue later.

**Review by linamnt — APPROVED** [review]

**Comment by linamnt** [comment]
I think this is more than enough for an hour, might not be worth showing Folium unless it were truly a quick demo?

**Review by lwjohnst86 — COMMENTED** [review]
Looks good overall. Only thing is that the first code chunk doesn't get rendered properly in markdown. Not sure why. Maybe put some text between the list and the first import?

**Comment by lwjohnst86** [comment]
Other thing. The lesson file size is hefty and, at least on my machine, is slow to load via jekyll serve. Could it be reduced some how? Like reduce the dpi/dimensions of the figures?

**Comment by QuLogic** [comment]
I think I'll just mention `folium` in passing then. I'll try and see if I can generate the markdown with external images.

**Comment by lwjohnst86** [comment]
That first code chunk is still rendered weird... What if you put it below the `# Setup` header?

**Comment by QuLogic** [comment]
I think it should be good now.

**Pull request merged**
