### PR TITLE
Edit site name and description

### PR DESCRIPTION
**Pull request by lwjohnst86**
This PR contains commits from a currently in process PR (on the lessons.md in the site), so don't merge until then.

I think as a title for a group, 'Study Group' is a bit ambiguous, so I'm proposing we change the site name to be the 'University of Toronto Scientific Coders', so it's more targeted. 

I've also changed the description of the group.

Both were done in the `_config.yml` file.

Thoughts?

### CODE REVIEW

**Comment by QuLogic** [comment]
I don't see anything wrong with this (except maybe it could be rebased.) @mbonsma?

**Comment by mbonsma** [comment]
'Study Group' is ambiguous, but maybe we should try to avoid using the label 'scientific coding' too much to not discourage coders who don't think they're scientists. But I could also be persuaded that all research using programming can be called science. Thoughts?

**Comment by lwjohnst86** [comment]
I juggled with that too. On the one hand, saying only 'coders' may attract 'true' programmers (ie: those in CS who are training to do programming as a career), but on the other hand, you are right, people in the humanities for instance may perceive the group as not related to them... Though I would argue just as you say, that using programming to do research is basically doing science, since it is a process/method.  I would say in general that a lot of humanities people probably do a lot more 'science' then they may realize...

Maybe I'll include within the description something about humanities and sciences or something... I'll sleep on it.

**Comment by mbonsma** [comment]
No rush. What about something like 'research coders'?

**Comment by QuLogic** [comment]
Of note is that the description doesn't really show anywhere visible. It's in the page metadata only.

**Comment by mbonsma** [comment]
@QuLogic okay, good point.

**Comment by lwjohnst86** [comment]
I've looked into this more and it seems more common to say scientific coding/coder vs research coder. If you do a google search of research coder, sites come up that are on categorical coding of data (0 = 'History', 2 = 'Arts', 3 = 'Comedy', etc) that are used in databases. But for scientific coding, the google results come up as would be anticipated (R, Python, etc.). So I think 'Scientific Coders' may be more appropriate.

**Comment by mbonsma** [comment]
Okay, I like it!

**Comment by lwjohnst86** [comment]
Cool, so you both good with me merging in? I know best practice is to not merge your own PR, but not sure how strict that is..?

**Comment by QuLogic** [comment]
Orrr, just wait a couple minutes...

**Comment by lwjohnst86** [comment]
Guess I was eager :smile:

**Pull request merged**
