### PR TITLE
SWC application cover letter

### PR DESCRIPTION
**Pull request by mbonsma**
This is supposed to be just commit e689a37 "Draft of cover letter", but it brought along another commit. I made a new branch before creating the cover letter to avoid this kind of thing, I thought. Heeelllp what happened?

### CODE REVIEW

**Comment by katieannemills** [comment]
First of all: gigantic high fives for pulling together the SWC training at U of T - UBC and SFU are doing the same, it's going to be awesome :)

Did you make the `SWC_app` branch from a branch that already had the commit `Merge branch 'Rstats_branch' into gh-pages` on it? That'd do it. When you make a PR, all commits not currently on the branch you're PR'ing to get set up for merge.

All that said, does this hurt anything? Assuming you want to merge all these changes, it shouldn't be a problem. Let me know how I can help!

**Comment by katieannemills** [comment]
> ~~All that said, does this hurt anything?~~

Oh duh I didn't notice the merge conflict at first, sorry :/ I'm not sure why the merge commit is causing problems, but if you want to not have it be part of this commit, we need to branch from a common ancestor, and cherry-pick your swc commit to that branch, then send a new pr:

`ea3` is the latest commit on both your `gh-pages`, and the main one, so this will probably be the least problematic place to start from:

```
git checkout gh-pages
git branch my-new-branch ea3e0520d91c9
git checkout my-new-branch
```

Now we want to move the swc commit onto this new branch. Cherry-pick to the rescue:

```
git cherry-pick e689a37
```

And you should have a commit history on `my-new-branch` with the swc commit as the latest and the create intro R_2 immediately preceding it. Assuming the swc changes don't bump into the merge commits (which they probably can't since they're brand new files), you will (hopefully) be able to pr from `mbonsma:my-new-branch` to `UofTCoders:gh-pages` as normal (and assuming I have gamed this out right in my mind :)

Let me know if that works!

**Comment by mbonsma** [comment]
Thanks! I think it worked!

**Comment by katieannemills** [comment]
huzzah!

**Pull request closed without merging**
