### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by SaraMati**

### CODE REVIEW

**Comment by QuLogic** [comment]
Was this caused by a bug in the script?

**Comment by SaraMati** [comment]
no, my lack of knowledge in R... I wanted the description variable to be empty. The code gave an error if I didn't assign anything to it, so I put quotation marks to create an empty string (or list?), but then these two quotation marks would be inside the template quotation marks that website builder has. hence, double quotation, hence the error. 
is that clear?

**Comment by lwjohnst86** [comment]
I should look into this to fix this problem...

**Comment by SaraMati** [comment]
no worries, I could simply put TBA for the description!

**Pull request merged**
