### PR TITLE
added codealong from session

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by QuLogic** [comment]
Can you rename to `lesson.md` so it gets HTML-ified on the website? Also, it will need to be proper Markdown with indented code and such.

**Comment by ghost** [comment]
okay all done :)

**Comment by QuLogic** [comment]
I think the file is missing the front matter so [it doesn't show up](https://qulogic.github.io/studyGroup/lessons/). Can you add that to your file? See [here](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/template/lesson.md).

**Comment by ghost** [comment]
okay i think it's good now

**Comment by QuLogic** [comment]
Nearly there, except Jekyll uses some _other_ Markdown format, so you need to wrap code in `~~~` instead of ```.

**Comment by ghost** [comment]
okay! lol I think she's done.

**Comment by QuLogic** [comment]
Just ooone more thing...

No, not really. :stuck_out_tongue:

**Pull request merged**
