### PR TITLE
Updated git lesson file

### PR DESCRIPTION
**Pull request by lwjohnst86**
In prep for next session, I've updated the git lesson file.

### CODE REVIEW

**Comment by QuLogic** [comment]
Ah, I was going to ask you about this, too. Many people seem to think that it's easier to learn git from the bottom-up vs top-down. That is, learning the data model vs just learning a bunch of commands. I'm not saying we should go too far in depth, but I think it might be useful to add some definitions during the introduction. As it stands there are a _lot_ of unknown terms thrown at people while at the same time teaching the commands that go along with them. A short overview before jumping in to the commands might be helpful there.

**Comment by lwjohnst86** [comment]
Hmm, yes, it probably would be a good idea to define the terms a bit more... by the way, I wanted to ask too, what are you planning to go over in the next session? So we can maybe synchronize or something. Also, what are your thoughts on going over GitHub/pushing and pulling in the intro? One hour is so little time... :disappointed:  

Not so sure about the bottom-up approach though. The bottom-up approach requires a lot of background knowledge (eg. how data is stored on a computer, graph theory, basic understanding of the command-line and what it's doing when you type commands, etc.). From what I've read and learned about learning in adults, they're more interested in learning a tool and how to apply it and why it's important to use/learn than in how it works... Take for instance how cell phones work, how fridges work, or even how cars work. Learning how git works will come as you use it. Given the importance of version control, especially in science, I think it's better to get more people using it first before getting them to understand how it works.

PS: it also depends on how you define bottom-up vs top-down!  I don't think the science has yet gotten a good answer yet for which is better.

**Comment by QuLogic** [comment]
I haven't really decided; I suppose it depends on how much you get through. Potentially, we could talk about GitHub, rebasing, (advanced) merging, navigating the log, in-depth staging, etc.

I don't think we need to go right to the _very_ bottom; something about what some of the terms mean should be enough. For example, a commit knows about its own parent(s), so that way you can "go back in time", but the fact that it creates a DAG and such is not too interesting. I might have a figure that will explain what I mean better.

**Comment by QuLogic** [comment]
I was thinking of something like [this slide](https://speakerdeck.com/qulogic/github-1?slide=24), but only labelling a few relevant things (e.g., working directory, a commit, a repository, _maybe_ a remote.)

**Comment by lwjohnst86** [comment]
Thanks @QuLogic for the slides, it gives me an idea on how to incorporate what you've said.

Regarding GitHub/pushing/pulling, I think I will only cover it if there is time at the end/depending on the group.

Thanks for the tips!

**Comment by ultush** [comment]
Hi there are two of us at MP 408
Did the location change?

**Comment by QuLogic** [comment]
I'm sorry to say, that it already happened yesterday. Next week will return to the regular Thursday schedule.

**Pull request merged**
