### PR TITLE
Logos

### PR DESCRIPTION
**Pull request by linamnt**

### CODE REVIEW

**Comment by lwjohnst86** [comment]
No issues here! But, what is `.psb`? Photoshop? Is it possible to get it in an `.svg` format as well? For other, non-Photoshop alternatives (eg. Inkscape)?

**Comment by linamnt** [comment]
Yeah sorry I forgot that wasn't an easily accessible filetype, I don't think it's usable in inkscape since I didn't use illustrator? I just removed it and added the main art I used taken from the internet.

**Comment by lwjohnst86** [comment]
Is it possible to save as a `.svg` file in illustrator? I have never used it so I don't know how it works. Or wait, you did use Illustrator or something else? Either way, I think it's possible to 'Save as' in the `svg` format.

**Comment by linamnt** [comment]
I think it's definitely possible in illustrator but these were made in
photoshop, not illustrator. I can't seem to find a way to save as svg in
the version of photoshop that I have (cs4)?

On Thu, Sep 17, 2015 at 3:54 PM, Luke W Johnston notifications@github.com
wrote:

> Is it possible to save as a .svg file in illustrator? I have never used
> it so I don't know how it works. Or wait, you did use Illustrator or
> something else? Either way, I think it's possible to 'Save as' in the svg
> format.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/pull/47#issuecomment-141207060.

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by QuLogic** [comment]
From what I've read, it looks like the CC version can export to SVG. Maybe you can also import into Illustrator and then export as SVG.

But I looked at the PSD; there are not too many layers. It might be easiest to recreate it in Inkscape directly.

**Comment by lwjohnst86** [comment]
Haha, well, that sounds like a lot more work than is maybe necessary (about recreating it)! I'm fine with how this is right now. Sorry that I didn't understand that you used Photoshop, it makes sense now.

**Comment by jladan** [comment]
The .psd file can also be opened in Gimp, which should be good enough. Maybe merge this pull request, and create an issue to make an svg version in the future.

**Comment by QuLogic** [comment]
I'm like 90% done with an SVG copy; I just need the text for the background. GIMP is not able to read the original text layer from the .psd file.

**Comment by lwjohnst86** [comment]
Excellent thanks @linamnt

**Pull request merged**
