### PR TITLE
Cleaned up some images and files not used

### PR DESCRIPTION
**Pull request by lwjohnst86**
This PR also has the PR commits for the lessons.md to be put on the site, so don't merge this until that PR has been merged.

There were several files that were not used, nor referenced anywhere in the repo, so I deleted them.

All the files were in the `img/` directory, as well as a few `_includes/` files such as `about.html`.

### CODE REVIEW

**Comment by lwjohnst86** [comment]
Yes they were... I had no idea what they were for...

**Comment by QuLogic** [comment]
You'll need to rebase since your other PR was merged.

**Comment by lwjohnst86** [comment]
Fixed.

**Comment by lwjohnst86** [comment]
Slightly related to cleaning up, but @QuLogic do you know why this code is included in the Jekyll code?

```
{{ site.github.url | replace: 'http', 'https' }}
```

For me, trying to view the https on my github account doesn't work correctly (www.lukewjohnston.com/studyGroup/). Inspecting the underlying code shows it using `https`, so if I explicitly use https://www.lukewjohnston.com/studyGroup, it says untrusted connection...

To me, I don't see why it should be `https` rather than regular `http`... it's not like we have sensitive data. Do you know why? Can we remove it?

**Comment by QuLogic** [comment]
It doesn't work for you because your site doesn't have a cert.

The studyGroup site didn't work before over https with HTTPS Everywhere because of the mixed content (it was basically the same as it looks to you now with http.) I _could_ have used protocol agnostic links, but current recommended practice is to just use https and upstream had no reason to do otherwise. GitHub Pages provide a cert and we also have no reason to use http, so we don't do it either.

**Comment by lwjohnst86** [comment]
Ooo, I see. That makes sense. Thanks. Now I just have to figure out how to get https working for my domain...

**Pull request merged**
