### PR TITLE
Changed updateCalendar.py with study group info

### PR DESCRIPTION
**Pull request by mbonsma**
I can now run updateCalendar.py locally and it automatically updates our Google Calendar based on the files in the _posts directory. I think it should be possible for anyone to run it and do the update, but I'm really not sure.

### CODE REVIEW

**Comment by mbonsma** [comment]
Actually, there's a file in my directory called `client_secret.json` that is probably needed for someone else to run it successfully? I'm not too familiar with how APIs work. Maybe only I can run the update script.

**Comment by lwjohnst86** [comment]
Well, whatever you end up doing, make sure to update your `calender_branch` with the upstream master branch to get rid of other commits from the previous PR.

**Comment by mbonsma** [comment]
Help. Do I rebase? Do I merge? I'm not sure how to get rid of those commits.

**Comment by lwjohnst86** [comment]
I usually just do:

```
git checkout calender_branch
git pull upstream calender_branch
```

That should be enough.

**Comment by lwjohnst86** [comment]
And then: 

```
git push origin calender_branch
```

**Comment by QuLogic** [comment]
> client_secret.json

Yes, don't make that public...

**Pull request merged**
