### PR TITLE
Fixed navbar links + added logo to site

### PR DESCRIPTION
**Pull request by lwjohnst86**
Added the logo to the site! And fixed the navbar links, which didn't work correctly when they were in the lesson content area.

### CODE REVIEW

**Comment by QuLogic** [comment]
Trying it out, but I'm not seeing the logo here: https://qulogic.github.io/studyGroup/lessons/

**Comment by lwjohnst86** [comment]
This fix worked on my local jekyll run. Yours?

**Comment by QuLogic** [comment]
Almost; it's missing the HTTPS so it triggers a non-secure warning.

**Comment by lwjohnst86** [comment]
Shit, forgot about that... done

**Comment by QuLogic** [comment]
We might need to tweak the colours a bit, but it looks fine so far.

**Pull request merged**
