### PR TITLE
Developed website material to show lessons.md

### PR DESCRIPTION
**Pull request by lwjohnst86**
Right now, the lesson material that shows up online is not super pretty. I've got it to work... but I'm not extremely competent with html/stylesheets, so if anyone ( @QuLogic ?) knows how to make this prettier, I'd love to fix the stuff up!

### CODE REVIEW

**Comment by QuLogic** [comment]
I'm not seeing any links to the lessons on the [generated site](https://qulogic.github.io/studyGroup). But if I go [there directly](https://qulogic.github.io/studyGroup/lessons/content/) all the links are not working.

**Comment by QuLogic** [comment]
Oh, scratch that first part; I hadn't refreshed late enough. But the link is still broken.

**Comment by lwjohnst86** [comment]
I know the problem. I've tried to fix it. See if that works.

**Comment by lwjohnst86** [comment]
@QuLogic Do you know why my gh-pages doesn't load? My local jekyll 'localhost:4000' works, but trying to get the gh-pages to load on my account is not working. Could it be related to setting up a CNAME on one of my other repos? It just redirects to the CNAME one, even though it is a gh-pages...

**Comment by QuLogic** [comment]
It seems like something with the CNAME; maybe there's a link somewhere that uses the wrong URL. See [this commit](https://github.com/QuLogic/studyGroup/commit/4453ef348a902d8f03b8d53cac08faadd121895b) for a better fix for lesson linking.

**Comment by lwjohnst86** [comment]
Thanks so much @QuLogic you made it look much prettier!

**Comment by QuLogic** [comment]
@mbonsma Please have a look; I don't like to merge PRs I've worked on myself.

**Comment by mbonsma** [comment]
If I go to @QuLogic's [version](https://qulogic.github.io/studyGroup), I get error 404 file not found. @lwjohnst86's page looks like this:

image

And if I click 'Lesson Content' it's broken.

Am I checking the right thing even? Heeelllp

**Comment by lwjohnst86** [comment]
Hrm, yea, you are checking the right thing. But mine I think does that because I have a domain pointed to my lwjohnst86.github.io repo, which I think is messing up other repos. Not sure how to fix it.

@QuLogic changed his repo to be master rather than gh-pages so it won't show up online.

Besides some command line magic, I am not sure how you will see it for yourself. Let me try something

**Comment by QuLogic** [comment]
Ah yep, sorry, I deleted the branch when I closed the PR on @lwjohnst86's repo and I forgot you might want to look at it yourself. My [copy](https://qulogic.github.io/studyGroup) should be visible once again.

**Comment by QuLogic** [comment]
@lwjohnst86 BTW, lwjohnst86.github.io redirects to lukewjohnston.com but that doesn't resolve. I could have sworn it redirected to something different yesterday.

**Comment by lwjohnst86** [comment]
Yea, I've been trying to fix an issue with my DNS. It was different before, good eye. 

On 12 August, 2015 4:40:32 PM EDT, Elliott Sales de Andrade notifications@github.com wrote:

> @lwjohnst86 BTW, lwjohnst86.github.io redirects to lukewjohnston.com
> but that doesn't resolve. I could have sworn it redirected to something
> different yesterday.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/UofTCoders/studyGroup/pull/36#issuecomment-130440883

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mbonsma** [comment]
Cool, it's working now. It looks awesome! My only comment is not technical - we should make sure each `lesson.md` file contains a pointer of some kind back to the repo so that people aren't confused by references to other files.

**Comment by lwjohnst86** [comment]
As per your suggestion @mbonsma I've added a link in each lesson to link to the location in the repo where the lesson content is found.

**Comment by QuLogic** [comment]
You missed your own `lesson.md`.

**Comment by lwjohnst86** [comment]
Really? Which one? I can't find it.

**Comment by QuLogic** [comment]
You've changed `lessons/introR/lesson.Rmd` (which isn't used on the website), but not `lessons/introR/lesson.md`.

**Comment by QuLogic** [comment]
Huh, wait, you did... I don't know why the website didn't refresh (even after a hard refresh.)

OK, another hard refresh and it's working. Don't know why it didn't work the first time when it did for the others.

**Comment by lwjohnst86** [comment]
Hrm, that is strange...

**Pull request merged**
