### PR TITLE
Create lesson.md file for intro to ruby

### PR DESCRIPTION
**Pull request by jennaleeb**

### CODE REVIEW

**Comment by mbonsma** [comment]
Awesome! I think it needs to be called 'lesson.md' specifically but I'm not positive - @lwjohnst86, can you comment?

**Comment by lwjohnst86** [comment]
Yes, it does. Otherwise it won't be picked up by the website list.

Just for completion of content and so it is up online on the site, is it possible to get the whole lesson material on here? Along with the link of the original lesson? Less clicking and moving around for those doing the lesson.

**Comment by jennaleeb** [comment]
Sure! I wasn't sure how to make a folder via a pull request? [Edit] Do I have to clone the whole repo?

**Comment by lwjohnst86** [comment]
PS: very pretty slides! Plus a pic of Jensen Ackles... nice haha.

For making the slides into a md version, it's fairly easy to do using pandoc, though not perfect. Just use the command:

```
pandoc slides.html -t markdown_github -o slides.md
```

You can then use the `slides.md` content and put it into the `lesson.md` file :smile:

**Comment by lwjohnst86** [comment]
Make sure to clean up any of the left over html tags that pandoc missed!

**Comment by jennaleeb** [comment]
Wish I could take credit - they are just a modification from [Ladies Learning Code](https://github.com/ladieslearningcode/Ruby) workshop. Ok will do!

**Pull request merged**
