### PR TITLE
Add a "Who We Are" page.

### PR DESCRIPTION
**Pull request by QuLogic**
I picked out a few people from the Watchers who have some information in their profile. You can see how it looks [here](https://qulogic.github.io/studyGroup/#team). A couple of points:
- It's sorted alphabetically by last name (easiest way to get @mbonsma first ;)
- I'm not sure what to call the byline key. It's currently `degree`, but e.g., @acabunoc doesn't exactly fall in that category.
- Avatars come from GitHub, so set a profile picture if you want your picture there.
- Names currently link to GitHub profile (or nowhere), but maybe that should be flexible (not hard to fix).
- @lwjohnst86 Filling in people's information seems like a good second step to do after getting through the git tutorial (but I still think they should work on a sandbox for tonight.)

### CODE REVIEW

**Comment by lwjohnst86** [comment]
Very coool! :+1:

**Comment by aerler** [comment]
You could add me as well; I just made an account; also Physics PhD. I wasn't able to come last time, but will come today.

**Comment by lannajin** [comment]
Was also unable to attend last time, but planning to be there in 20 minutes--Ecology & Evolutionary Biology, PhD Candidate.

**Comment by QuLogic** [comment]
You can add yourselves after the tutorial; I did not add even close to all the people yet...

**Comment by QuLogic** [comment]
I added information for everyone who opened a PR during the tutorial. It's still only about 50% of the people who are watching this repo though.

**Pull request merged**
