### PR TITLE
Added SWC R event

### PR DESCRIPTION
**Pull request by dcwalk**
Could you please review and lemme know if I need to make changes? 

Especially wasn't sure how to add a multi-day event using a post-- is that possible?

### CODE REVIEW

**Comment by mbonsma** [comment]
Good question - I don't know if it's possible to make it multi-day. @BillMills, @QuLogic - is that possible? I don't think it's super critical if it's not easy to do.

Other than that, it all looks good!

**Comment by QuLogic** [comment]
I don't think it's possible to make it multi-day; the code appears to just look for a single `date` field in the metadata. Maybe just make two events for Day 1 and Day 2.

**Comment by dcwalk** [comment]
@QuLogic thanks for verifying! 

Do we need to have two events? Or if we update the title text to indicate better it is two days would that be enough?

**Comment by dcwalk** [comment]
Okay, made a slight update, but I think it is fine to work with just one event per workshop (hope that works for everyone!)

**Comment by mbonsma** [comment]
@dcwalk, I agree - one post per event is good. As soon as you click on it you're taken to the website anyway.

**Comment by dcwalk** [comment]
cool! I can't merge in, @mbonsma if there are no blocks do you mind?

**Pull request merged**
